#!/bin/bash

echo "Starting the experiments"
# python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 1 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m cnn_zaid0 -v 1 --with-regularization --record ASCAD_HW_garbage --record-trials 1 --record-axis na -i DIM_1_zaid0
# python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 1 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m cnn_zaid50 -v 1 --with-regularization --record ASCAD_HW_newPlots --record-trials 1 --record-axis na -i DIM_1_zaid50
# python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 1 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m cnn_zaid100 -v 1 --with-regularization --record ASCAD_HW_newPlots --record-trials 1 --record-axis na -i DIM_1_zaid100
# python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 1 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m no_conv0 -v 1 --with-regularization --record ASCAD_HW_newPlots --record-trials 1 --record-axis na -i DIM_1_noconv0
# python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 1 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m no_conv50 -v 1 --with-regularization --record ASCAD_HW_newPlots --record-trials 1 --record-axis na -i DIM_1_noconv50
# python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 1 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m no_conv100 -v 1 --with-regularization --record ASCAD_HW_newPlots --record-trials 1 --record-axis na -i DIM_1_noconv100



# python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 0 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m cnn_zaid0 -v 1 --with-regularization --record ASCAD_HW_garbage --record-trials 1 --record-axis na -i DIM_0_zaid0
# python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 0 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m cnn_zaid50 -v 1 --with-regularization --record ASCAD_HW_newPlots --record-trials 1 --record-axis na -i DIM_0_zaid50
# python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 0 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m cnn_zaid100 -v 1 --with-regularization --record ASCAD_HW_newPlots --record-trials 1 --record-axis na -i DIM_0_zaid100
# python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 0 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m no_conv0 -v 1 --with-regularization --record ASCAD_HW_newPlots --record-trials 1 --record-axis na -i DIM_0_noconv0
# python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 0 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m no_conv50 -v 1 --with-regularization --record ASCAD_HW_newPlots --record-trials 1 --record-axis na -i DIM_0_noconv50
# python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 0 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m no_conv100 -v 1 --with-regularization --record ASCAD_HW_newPlots --record-trials 1 --record-axis na -i DIM_0_noconv100



python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 1 -e 5 --lm HW --loss nll --optimizer RMSprop --lr --lc SBox -m cnn_zaid0 -v 1 --with-regularization --record ASCAD_HW_f10 --record-trials 10 --record-axis na -i DIM_1_zaid0
python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 1 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m cnn_zaid50 -v 1 --with-regularization --record ASCAD_HW_f10 --record-trials 10 --record-axis na -i DIM_1_zaid50
python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 1 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m cnn_zaid100 -v 1 --with-regularization --record ASCAD_HW_f10 --record-trials 10 --record-axis na -i DIM_1_zaid100
python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 1 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m no_conv0 -v 1 --with-regularization --record ASCAD_HW_f10 --record-trials 10 --record-axis na -i DIM_1_noconv0
python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 1 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m no_conv50 -v 1 --with-regularization --record ASCAD_HW_f10 --record-trials 10 --record-axis na -i DIM_1_noconv50
python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 1 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m no_conv100 -v 1 --with-regularization --record ASCAD_HW_f10 --record-trials 10 --record-axis na -i DIM_1_noconv100



python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 0 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m cnn_zaid0 -v 1 --with-regularization --record ASCAD_HW_f10 --record-trials 10 --record-axis na -i DIM_0_zaid0
python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 0 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m cnn_zaid50 -v 1 --with-regularization --record ASCAD_HW_f10 --record-trials 10 --record-axis na -i DIM_0_zaid50
python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 0 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m cnn_zaid100 -v 1 --with-regularization --record ASCAD_HW_f10 --record-trials 10 --record-axis na -i DIM_0_zaid100
python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 0 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m no_conv0 -v 1 --with-regularization --record ASCAD_HW_f10 --record-trials 10 --record-axis na -i DIM_0_noconv0
python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 0 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m no_conv50 -v 1 --with-regularization --record ASCAD_HW_f10 --record-trials 10 --record-axis na -i DIM_0_noconv50
python main.py -a 1000 -t 50000 -b 2 --batch-size 100 --pd /path/to/datasets/ -f ASCAD.h5 --pr /path/to/resultsresults/prof_paper -d 0 -e 5 --lm HW --loss nll --optimizer RMSprop --lc SBox -m no_conv100 -v 1 --with-regularization --record ASCAD_HW_f10 --record-trials 10 --record-axis na -i DIM_0_noconv100